name: Check file diffs
description: Compare files with git diff and produce a patch if they differ
inputs:
  compare_paths:
    description: Space-separated list of files/paths to compare with git diff
    required: true
  patch_path:
    description: Path to write the patch file
    required: false
    default: file_diff.patch
  error_message:
    description: Custom error message to display if files differ
    required: false
    default: "Files have changed"
runs:
  using: composite
  steps:
    - id: check
      name: Check for diffs and write patch
      shell: bash
      run: |
        set -e
        rc=0
        git --no-pager diff --exit-code ${{ inputs.compare_paths }} > ${{ inputs.patch_path }} 2> file_diff.err || rc=$?
        if [ "$rc" -eq 0 ]; then
          echo "changed=false" >> $GITHUB_OUTPUT
          rm -f file_diff.err || true
        elif [ "$rc" -eq 1 ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Patch size: $(wc -c < ${{ inputs.patch_path }}) bytes"
          echo "${{ inputs.error_message }}"
          echo "--- Diff ---"
          cat ${{ inputs.patch_path }} || true
          rm -f file_diff.err || true
        else
          echo "git diff failed with exit code $rc" >&2
          echo "--- git diff stderr ---" >&2
          cat file_diff.err >&2 || true
          exit $rc
        fi
        echo "patch_path=${{ inputs.patch_path }}" >> $GITHUB_OUTPUT

outputs:
  changed:
    description: 'true if files differ'
    value: ${{ steps.check.outputs.changed }}
  patch_path:
    description: 'path to generated patch file'
    value: ${{ steps.check.outputs.patch_path }}
