from interpretune.utils.exceptions import MisconfigurationException
from interpretune.utils.import_utils import (
    package_available,
    module_available,
    compare_version,
    _TORCH_GREATER_EQUAL_2_2,
    _DOTENV_AVAILABLE,
    _LIGHTNING_AVAILABLE,
    _FTS_AVAILABLE,
    _BNB_AVAILABLE,
    _SL_AVAILABLE,
    _CT_AVAILABLE,
    _NEURONPEDIA_AVAILABLE,
    _NNSIGHT_AVAILABLE,
)
from interpretune.utils.logging import (
    rank_zero_only,
    rank_zero_debug,
    rank_zero_info,
    rank_zero_warn,
    rank_zero_deprecation,
    collect_env_info,
    _get_rank,
)
from interpretune.utils.schema_validation import RemoveAdditionalPropertiesValidator
from interpretune.utils.tokenization import DEFAULT_DECODE_KWARGS, sanitize_input_name
from interpretune.utils.warnings import unexpected_state_msg_suffix, tl_invalid_dmap, dummy_method_warn_fingerprint
from interpretune.utils.data_movement import to_device, move_data_to_device
from interpretune.utils.import_utils import _import_class, instantiate_class, _resolve_dtype, resolve_funcs
from interpretune.utils.neuronpedia_db_utils import (
    DEFAULT_LOCAL_NEURONPEDIA_WEBAPP_URL,
    LocalNeuronpediaServiceStatus,
    NeuronpediaDBError,
    NeuronpediaExportBundleSummary,
    NeuronpediaLocalImportSummary,
    check_local_neuronpedia_services,
    import_neuronpedia_export_bundle_local_db,
    resolve_local_neuronpedia_db_url,
    rewrite_container_postgres_url_for_host,
    summarize_neuronpedia_export_bundle,
    summarize_neuronpedia_export_bundle_parquet,
)
from interpretune.utils.neuronpedia_explanations import (
    DEFAULT_NEURONPEDIA_BASE_URL,
    DEFAULT_NEURONPEDIA_PUBLIC_DATASET_BASE_URL,
    DEFAULT_COPILOT_TIMEOUT_SECONDS,
    DEFAULT_COPILOT_MODEL,
    DEFAULT_COPILOT_MAX_RETRIES,
    DEFAULT_COPILOT_RETRY_BACKOFF_SECONDS,
    DEFAULT_GENERATED_OUTPUT_DIR,
    DEFAULT_IT_NP_CACHE,
    DEFAULT_EXPLANATION_TYPE_NAME,
    DEFAULT_EXPLANATION_AUTHOR_ID,
    NeuronpediaFeatureRef,
    NeuronpediaPromptInputs,
    NeuronpediaExplanationImportArtifact,
    NeuronpediaExplanationArtifact,
    NeuronpediaExplanationError,
    NeuronpediaLocalExplanationStatus,
    NeuronpediaLocalExplanationCoverage,
    activation_batch_number,
    candidate_activation_batch_sizes,
    parse_feature_url,
    build_feature_ref,
    feature_tuples_to_feature_refs,
    default_np_cache_dir,
    cached_activation_batch_path,
    candidate_cached_activation_batch_paths,
    public_activation_batch_url,
    candidate_public_activation_batch_urls,
    ensure_cached_activation_batch,
    fetch_feature_payload,
    load_feature_payload_with_cached_activations,
    load_activation_batch_records,
    load_cached_feature_activations,
    derive_np_max_act_logits_inputs,
    build_explanation_prompt,
    build_np_max_act_logits_prompt,
    clean_explanation_text,
    artifact_output_path,
    build_explanation_export_record,
    write_explanation_import_bundle,
    insert_explanation_record_local_db,
    check_local_explanation_coverage,
    ensure_local_feature_explanations,
    generate_explanation_artifact,
    invoke_copilot_cli_with_retries,
)
from interpretune.utils.neuronpedia_dashboard_pipeline import (
    NeuronpediaDashboardLayerResult,
    NeuronpediaDashboardPipelineConfig,
    completed_layers_from_logs,
    convert_dashboard_output,
    run_dashboard_pipeline,
)

__all__ = [
    # exceptions
    "MisconfigurationException",
    # import_utils
    "package_available",
    "module_available",
    "compare_version",
    "_TORCH_GREATER_EQUAL_2_2",
    "_DOTENV_AVAILABLE",
    "_LIGHTNING_AVAILABLE",
    "_FTS_AVAILABLE",
    "_BNB_AVAILABLE",
    "_SL_AVAILABLE",
    "_CT_AVAILABLE",
    "_NEURONPEDIA_AVAILABLE",
    "_NNSIGHT_AVAILABLE",
    "_import_class",
    "instantiate_class",
    "_resolve_dtype",
    "resolve_funcs",
    # logging
    "rank_zero_only",
    "rank_zero_debug",
    "rank_zero_info",
    "rank_zero_warn",
    "rank_zero_deprecation",
    "collect_env_info",
    "_get_rank",
    # tokenization
    "DEFAULT_DECODE_KWARGS",
    "sanitize_input_name",
    # warnings
    "unexpected_state_msg_suffix",
    "tl_invalid_dmap",
    "dummy_method_warn_fingerprint",
    # data_movement
    "to_device",
    "move_data_to_device",
    # schema_validation
    "RemoveAdditionalPropertiesValidator",
    # neuronpedia_explanations
    "DEFAULT_NEURONPEDIA_BASE_URL",
    "DEFAULT_NEURONPEDIA_PUBLIC_DATASET_BASE_URL",
    "DEFAULT_COPILOT_TIMEOUT_SECONDS",
    "DEFAULT_COPILOT_MODEL",
    "DEFAULT_COPILOT_MAX_RETRIES",
    "DEFAULT_COPILOT_RETRY_BACKOFF_SECONDS",
    "DEFAULT_GENERATED_OUTPUT_DIR",
    "DEFAULT_IT_NP_CACHE",
    "DEFAULT_LOCAL_NEURONPEDIA_WEBAPP_URL",
    "DEFAULT_EXPLANATION_TYPE_NAME",
    "DEFAULT_EXPLANATION_AUTHOR_ID",
    "NeuronpediaFeatureRef",
    "NeuronpediaPromptInputs",
    "NeuronpediaExplanationImportArtifact",
    "NeuronpediaExplanationArtifact",
    "NeuronpediaExplanationError",
    "NeuronpediaDBError",
    "NeuronpediaExportBundleSummary",
    "LocalNeuronpediaServiceStatus",
    "NeuronpediaLocalImportSummary",
    "NeuronpediaLocalExplanationStatus",
    "NeuronpediaLocalExplanationCoverage",
    "activation_batch_number",
    "candidate_activation_batch_sizes",
    "parse_feature_url",
    "build_feature_ref",
    "feature_tuples_to_feature_refs",
    "default_np_cache_dir",
    "cached_activation_batch_path",
    "candidate_cached_activation_batch_paths",
    "public_activation_batch_url",
    "candidate_public_activation_batch_urls",
    "ensure_cached_activation_batch",
    "fetch_feature_payload",
    "load_feature_payload_with_cached_activations",
    "load_activation_batch_records",
    "load_cached_feature_activations",
    "derive_np_max_act_logits_inputs",
    "build_explanation_prompt",
    "build_np_max_act_logits_prompt",
    "clean_explanation_text",
    "artifact_output_path",
    "build_explanation_export_record",
    "write_explanation_import_bundle",
    "insert_explanation_record_local_db",
    "rewrite_container_postgres_url_for_host",
    "resolve_local_neuronpedia_db_url",
    "check_local_neuronpedia_services",
    "summarize_neuronpedia_export_bundle",
    "summarize_neuronpedia_export_bundle_parquet",
    "import_neuronpedia_export_bundle_local_db",
    "check_local_explanation_coverage",
    "ensure_local_feature_explanations",
    "generate_explanation_artifact",
    "invoke_copilot_cli_with_retries",
    # neuronpedia_dashboard_pipeline
    "NeuronpediaDashboardLayerResult",
    "NeuronpediaDashboardPipelineConfig",
    "completed_layers_from_logs",
    "convert_dashboard_output",
    "run_dashboard_pipeline",
]
