it_session:
  session_cfg:
    init_args:
      datamodule_cfg:
        class_path: interpretune.base.config.datamodule.ITDataModuleConfig
        init_args:
          enable_datasets_cache: false
          # for tlens we must set signature columns because the inspected model forward signature (HF) prior to setup will
          # differ from HookedTransformer's forward
          signature_columns: ['input', 'attention_mask', 'labels']
          tokenizer_kwargs:
            model_input_names: ['input', 'attention_mask']
