session_cfg:
  module_cfg:
    init_args:
      debug_lm_cfg:  # enable lm debugging connector features
        class_path: interpretune.extensions.debug_generation.DebugLMConfig
        init_args:
          enabled: true
          raw_debug_sequences:
          - How many days in a week?
          - How old is Barack Obama?
