name: "Install CI Dependencies"
description: "Install Python dependencies for CI workflows"

inputs:
  python_version:
    description: "Python version to use"
    required: false
    default: "3.12"
  show_pip_list:
    description: "Whether to show package list output after installations"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python_version }}
        activate-environment: true
        enable-cache: true

    - name: Install project dependencies
      shell: bash
      run: |
        # interpretune editable with git-deps group (uv doesn't currently support url deps in locked reqs)
        echo "Installing interpretune in editable mode with any git url dependencies..."
        uv pip install -e . --group git-deps
        echo "Installing locked CI requirements..."
        uv pip install -r requirements/ci/requirements.txt


    - name: Show package list
      if: inputs.show_pip_list == 'true'
      shell: bash
      run: |
        uv pip list
