blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/speediedan/interpretune/discussions/new
    about: Ask and answer interpretability and mechanistic interpretability related questions
