from typing import List, Literal
from copy import deepcopy
from functools import reduce, partial
import pytest

import torch
from torch.testing import assert_close
from transformer_lens.ActivationCache import ActivationCache
from transformer_lens.utils import get_device as tl_get_device
from sae_lens.saes.sae import SAE, SAEMetadata
from sae_lens.saes.transcoder import Transcoder, TranscoderConfig

from interpretune.utils import MisconfigurationException
from interpretune.session import ITSession
from interpretune.config import (
    SAELensFromPretrainedConfig,
    SAELensConfig,
    SAELensCustomConfig,
    ITLensFromPretrainedConfig,
    ITLensCustomConfig,
)
from interpretune.config.nnsight import NNsightConfig
from interpretune.config.transformer_lens import ITLensBridgeConfig
from tests.utils import ablate_cls_attrs
from tests.base_defaults import default_test_task
from tests.runif import RunIf

# Add new imports for mocking
from unittest.mock import patch, MagicMock, call


# simple counter hook
class Counter:
    def __init__(self):
        self.count = 0

    def inc(self, *args, **kwargs):  # type: ignore
        self.count += 1


def _sae_hook_name(model, sae_handle, internal="hook_sae_acts_post"):
    """Build SAE internal hook name, resolving aliases for Bridge models.

    HookedTransformer uses alias-based hook names (e.g., blocks.0.hook_resid_pre) while TransformerBridge resolves them
    to canonical names (e.g., blocks.0.hook_in). SAE internal hooks are registered at the resolved path, so cache
    lookups and hook targeting must use the resolved name.

    Delegates to SAETransformerBridge.get_sae_hook_name() when available (Bridge models), otherwise constructs the
    compound name directly (HookedTransformer models).
    """
    if hasattr(model, "get_sae_hook_name"):
        return model.get_sae_hook_name(sae_handle, internal)
    return f"{sae_handle.cfg.metadata.hook_name}.{internal}"


# TODO: change the fixtures below to be generated by a fixture factory if adding additional variants
#       (keeping explicit for now given the simplicity/efficiency tradeoff)
@pytest.fixture(scope="class")
def sl_ht_gpt2_w_ref_logits(get_it_session__sl_ht_gpt2__initonly):
    fixture = get_it_session__sl_ht_gpt2__initonly
    sl_test_module = fixture.it_session.module
    return sl_test_module, TestClassSAELens.get_ref_logits(sl_test_module)


@pytest.fixture(scope="class")
def sl_br_gpt2_w_ref_logits(get_it_session__sl_br_gpt2__initonly):
    fixture = get_it_session__sl_br_gpt2__initonly
    sl_test_module = fixture.it_session.module
    return sl_test_module, TestClassSAELens.get_ref_logits(sl_test_module)


@pytest.fixture(scope="class")
def l_sl_ht_gpt2_w_ref_logits(get_it_session__l_sl_ht_gpt2__initonly):
    fixture = get_it_session__l_sl_ht_gpt2__initonly
    sl_test_module = fixture.it_session.module
    return sl_test_module, TestClassSAELens.get_ref_logits(sl_test_module)


# NOTE: Hook-name-sensitive tests (cache_fwd_bwd, run_with_cache, run_with_hooks) now work with both
# HookedTransformer and TransformerBridge via _sae_hook_name() which resolves the hook alias
# (e.g. blocks.0.hook_resid_pre → blocks.0.hook_in) for Bridge models. Bridge SAE functionality is
# additionally covered by TestBridgeSAEBackend, TestCrossBackendSAEInit, and TestBridgeTranscoderSupport.
# Primary parametrization including HookedTransformer, TransformerBridge, and Lightning backends.
# Hook-name-sensitive tests use _sae_hook_name() to resolve aliases for Bridge models.
core_l_bridge_run_w_pytest_cfg = {
    "argvalues": [
        pytest.param("sl_ht_gpt2_w_ref_logits"),
        pytest.param("sl_br_gpt2_w_ref_logits"),
        pytest.param("l_sl_ht_gpt2_w_ref_logits", marks=RunIf(lightning=True)),
    ],
    "ids": ["core", "core_bridge", "lightning"],
}


class TestClassSAELens:
    sl_tokenizer_kwargs = {
        "add_bos_token": True,
        "local_files_only": False,
        "padding_side": "left",
        "model_input_names": ["input_ids", "attention_mask"],
    }
    test_sl_signature_columns = [
        "inputs",
        "attention_mask",
        "position_ids",
        "past_key_values",
        "inputs_embeds",
        "labels",
        "use_cache",
        "output_attentions",
        "output_hidden_states",
        "return_dict",
    ]
    test_tl_gpt2_shared_config = dict(
        task_name=default_test_task,
        tokenizer_kwargs=sl_tokenizer_kwargs,
        model_name_or_path="gpt2",
        tokenizer_id_overrides={"pad_token_id": 50256},
    )
    test_tlens_gpt2 = {
        **test_tl_gpt2_shared_config,
        "tl_cfg": ITLensFromPretrainedConfig(use_bridge=False),
        "hf_from_pretrained_cfg": dict(
            pretrained_kwargs={"device_map": "cpu", "dtype": "float32"}, model_head="transformers.GPT2LMHeadModel"
        ),
    }
    test_sl_from_pretrained = SAELensFromPretrainedConfig(
        release="gpt2-small-res-jb", sae_id="blocks.0.hook_resid_pre", device="cpu"
    )
    # tiny custom tl model to attach custom SAE to
    test_tl_cust_config = {
        "n_layers": 1,
        "d_mlp": 10,
        "d_model": 10,
        "d_head": 5,
        "n_heads": 2,
        "n_ctx": 200,
        "act_fn": "relu",
        "tokenizer_name": "gpt2",
    }

    test_sae_metadata = SAEMetadata(
        model_name="cust", hook_name="blocks.0.hook_resid_pre", hook_head_index=None, context_size=200, prepend_bos=True
    )
    test_sae_cust_config = dict(
        architecture="standard",
        d_in=10,
        d_sae=10 * 2,
        dtype="float32",
        device="cpu",
        normalize_activations="none",
        metadata=test_sae_metadata,
    )
    test_sl_cust_config = SAELensCustomConfig(cfg=test_sae_cust_config)
    test_sl_ht_gpt2 = {**test_tl_gpt2_shared_config, **test_tlens_gpt2, "sae_cfgs": test_sl_from_pretrained}
    test_sl_cust = {
        **test_tl_gpt2_shared_config,
        "tl_cfg": ITLensCustomConfig(cfg=test_tl_cust_config),
        "sae_cfgs": test_sl_cust_config,
    }
    prompt = "hello world"

    @staticmethod
    def get_ref_logits(test_module):
        return test_module.model(TestClassSAELens.prompt)

    def test_from_pretrained_device_init(self):
        test_sl_from_pretrained = SAELensFromPretrainedConfig(
            release="gpt2-small-res-jb", sae_id="blocks.0.hook_resid_pre", device=None
        )
        assert test_sl_from_pretrained.device == str(tl_get_device())

    @pytest.mark.parametrize("session_fixture", **core_l_bridge_run_w_pytest_cfg)
    def test_run_with_saes_with_cache_fwd_bwd(self, request, session_fixture):
        sl_test_module, _ = request.getfixturevalue(session_fixture)
        assert sl_test_module.model.unembed.b_U.requires_grad, (
            "Previous fixture may have polluted this test, requires_grad should be True"
        )
        filter_sae_acts = lambda name: "hook_sae_acts_post" in name
        cache_dict = {"fwd": {}, "bwd": {}}
        # TODO: maybe add a metric to extend test/make it more realistic

        def cache_hook(act, hook, dir: Literal["fwd", "bwd"]):
            cache_dict[dir][hook.name] = act.detach()

        with sl_test_module.model.saes(saes=sl_test_module.sae_handles):
            # We add hooks to cache values from the forward and backward pass respectively
            with sl_test_module.model.hooks(
                fwd_hooks=[(filter_sae_acts, partial(cache_hook, dir="fwd"))],
                bwd_hooks=[(filter_sae_acts, partial(cache_hook, dir="bwd"))],
            ):
                # fill fwd/bwd cache, hooks then removed on cm exit
                out = sl_test_module.model(TestClassSAELens.prompt)

                # Verify gradients are enabled before backward pass
                # assert out.requires_grad, "Output tensor does not have requires_grad=True"
                out[0, -1, 42].backward()

        cache_dict = {k: ActivationCache(cache_dict[k], sl_test_module.model) for k in cache_dict.keys()}
        for cache in cache_dict.values():
            assert isinstance(cache, ActivationCache)
            for sae_handle in sl_test_module.sae_handles:
                assert _sae_hook_name(sl_test_module.model, sae_handle) in cache

    @pytest.mark.parametrize("session_fixture", **core_l_bridge_run_w_pytest_cfg)
    def test_run_with_saes(self, request, session_fixture):
        sl_test_module, original_logits = request.getfixturevalue(session_fixture)
        assert len(sl_test_module.model.acts_to_saes) == 0
        logits_with_saes = sl_test_module.model.run_with_saes(TestClassSAELens.prompt, saes=sl_test_module.sae_handles)
        assert len(sl_test_module.model.acts_to_saes) == 0
        assert not torch.allclose(logits_with_saes, original_logits)

    @pytest.mark.parametrize("session_fixture", **core_l_bridge_run_w_pytest_cfg)
    def test_run_with_cache_with_saes(self, request, session_fixture):
        sl_test_module, original_logits = request.getfixturevalue(session_fixture)
        assert len(sl_test_module.model.acts_to_saes) == 0
        logits_with_saes, cache = sl_test_module.model.run_with_cache_with_saes(
            TestClassSAELens.prompt, saes=sl_test_module.sae_handles
        )
        assert not torch.allclose(logits_with_saes, original_logits)
        assert isinstance(cache, ActivationCache)
        for sae_handle in sl_test_module.sae_handles:
            assert _sae_hook_name(sl_test_module.model, sae_handle) in cache

    @pytest.mark.parametrize("session_fixture", **core_l_bridge_run_w_pytest_cfg)
    def test_run_with_hooks_with_saes(self, request, session_fixture):
        sl_test_module, original_logits = request.getfixturevalue(session_fixture)
        c = Counter()
        assert len(sl_test_module.model.acts_to_saes) == 0
        logits_with_saes = sl_test_module.model.run_with_hooks_with_saes(
            TestClassSAELens.prompt,
            saes=sl_test_module.sae_handles,
            fwd_hooks=[
                (_sae_hook_name(sl_test_module.model, sae_handle), c.inc) for sae_handle in sl_test_module.sae_handles
            ],
        )
        assert not torch.allclose(logits_with_saes, original_logits)
        assert c.count == len(sl_test_module.sae_handles)

    @pytest.mark.parametrize(
        "session_fixture",
        [
            pytest.param("get_it_session__l_sl_ht_gpt2__initonly", marks=RunIf(lightning=True), id="lightning_ht"),
            pytest.param("get_it_session__sl_br_gpt2__initonly", id="core_bridge"),
        ],
    )
    def test_sl_module_warns(self, request, session_fixture):
        fixture = request.getfixturevalue(session_fixture)
        sl_test_module = fixture.it_session.module
        with ablate_cls_attrs(sl_test_module.it_cfg, "sae_cfgs"), pytest.warns(UserWarning, match="Could not find a"):
            _ = sl_test_module.sae_cfgs

    @staticmethod
    def cfg_saes_like(orig_sae_cfg, new_hook_points: List):
        new_sae_cfgs = []
        sae_attr = "sae_id" if isinstance(orig_sae_cfg, SAELensFromPretrainedConfig) else "cfg.hook_name"
        for hook_override in new_hook_points:
            new_sae_cfg = deepcopy(orig_sae_cfg)
            attr_parts = sae_attr.rpartition(".")
            new_sae_cfg_ref = reduce(getattr, attr_parts[0].split("."), new_sae_cfg) if attr_parts[0] else new_sae_cfg
            setattr(new_sae_cfg_ref, attr_parts[-1], hook_override)
            new_sae_cfgs.append(new_sae_cfg)
        return new_sae_cfgs

    @pytest.mark.parametrize(
        "session_cfg_fixture, sl_pretrained, add_saes_on_init",
        [
            pytest.param("get_it_session_cfg__sl_ht_gpt2", False, False),
            pytest.param("get_it_session_cfg__sl_ht_gpt2", False, True),
            pytest.param("get_it_session_cfg__sl_ht_gpt2", True, False),
            pytest.param("get_it_session_cfg__sl_ht_gpt2", True, True),
            pytest.param("get_it_session_cfg__sl_cust", False, False),
            pytest.param("get_it_session_cfg__sl_cust", False, True),
            pytest.param("get_it_session_cfg__sl_br_gpt2", False, False),
            pytest.param("get_it_session_cfg__sl_br_gpt2", False, True),
            pytest.param("get_it_session_cfg__sl_br_gpt2", True, False),
            pytest.param("get_it_session_cfg__sl_br_gpt2", True, True),
        ],
        ids=[
            "tlpre_slcust_noadd",
            "tlpre_slcust_add",
            "tlpre_slgpt2_noadd",
            "tlpre_slgpt2_add",
            "tlcust_slcust_noadd",
            "tlcust_slcust_add",
            "bridge_slcust_noadd",
            "bridge_slcust_add",
            "bridge_slgpt2_noadd",
            "bridge_slgpt2_add",
        ],
    )
    def test_sl_module_init(self, request, session_cfg_fixture, sl_pretrained, add_saes_on_init):
        it_session_cfg = request.getfixturevalue(session_cfg_fixture)
        sess_cfg = deepcopy(it_session_cfg)
        if not sl_pretrained:
            sess_cfg.module_cfg.sae_cfgs = [TestClassSAELens.test_sl_cust_config]
        sess_cfg.module_cfg.add_saes_on_init = add_saes_on_init
        test_mod = ITSession(sess_cfg).module
        expected_num_saes = len(sess_cfg.module_cfg.sae_cfgs)
        if add_saes_on_init:
            assert len(test_mod.model.acts_to_saes) == expected_num_saes
            assert test_mod.model.acts_to_saes[test_mod.it_cfg.normalized_sae_cfg_refs[-1]] == test_mod.sae_handles[-1]
        else:
            assert len(test_mod.model.acts_to_saes) == 0
        assert len(test_mod.sae_handles) == len(test_mod.saes) == expected_num_saes

    def test_sl_basic_cfg(self):
        test_sl_cfg = deepcopy(TestClassSAELens.test_sl_cust)
        it_cfg = SAELensConfig(**test_sl_cfg)
        assert it_cfg
        test_sl_cfg.update({"sae_cfgs": None})
        with pytest.raises(MisconfigurationException, match="At least one `SAELens"):
            _ = SAELensConfig(**test_sl_cfg)

    @RunIf(min_cuda_gpus=1)
    def test_sl_tl_device_sync_warnings(self):
        test_sl_cfg = deepcopy(TestClassSAELens.test_sl_cust)
        with pytest.warns(UserWarning, match=r"This SAEConfig's device type \('cpu'\) does not match the"):
            it_cfg = SAELensConfig(**test_sl_cfg)
        assert isinstance(it_cfg, SAELensConfig)
        assert it_cfg.sae_cfgs[0].cfg.device in ["cuda", "mps"]
        test_sl_cfg["sae_cfgs"].cfg.device = None
        with pytest.warns(UserWarning, match=r"An SAEConfig device type was not provided"):
            it_cfg = SAELensConfig(**test_sl_cfg)
        assert isinstance(it_cfg, SAELensConfig)
        assert it_cfg.sae_cfgs[0].cfg.device in ["cuda", "mps"]

    @patch("interpretune.adapters.sae_lens.get_pretrained_saes_directory")
    @patch("interpretune.adapters.sae_lens.display")
    @patch("interpretune.adapters.sae_lens.IFrame")
    @patch("interpretune.adapters.sae_lens.print")
    def test_display_dashboard(self, mock_print, mock_iframe, mock_display, mock_get_dir):
        """Test the display_dashboard static method."""
        # Setup mock directory response
        mock_release = MagicMock()
        mock_release.neuronpedia_id = {"blocks.9.hook_resid_pre": "test-neuronpedia-id"}
        mock_get_dir.return_value = {"gpt2-small-res-jb": mock_release}

        # Call the method with default parameters
        from interpretune.adapters.sae_lens import SAELensAnalysisMixin

        SAELensAnalysisMixin.display_dashboard()

        # Verify URL construction and IFrame parameters
        expected_url = "https://neuronpedia.org/test-neuronpedia-id/0?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300"
        mock_print.assert_called_with(expected_url)
        mock_iframe.assert_called_with(expected_url, width=800, height=600)
        mock_display.assert_called_once()

        # Test with custom parameters
        mock_print.reset_mock()
        mock_iframe.reset_mock()
        mock_display.reset_mock()

        SAELensAnalysisMixin.display_dashboard(
            sae_release="gpt2-small-res-jb", sae_id="blocks.9.hook_resid_pre", latent_idx=42, width=1000, height=700
        )

        expected_url = "https://neuronpedia.org/test-neuronpedia-id/42?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300"
        mock_print.assert_called_with(expected_url)
        mock_iframe.assert_called_with(expected_url, width=1000, height=700)
        mock_display.assert_called_once()

    @patch("interpretune.adapters.sae_lens.SAELensAnalysisMixin.display_dashboard")
    @patch("interpretune.adapters.sae_lens.print")
    def test_display_latent_dashboards(self, mock_print, mock_display_dashboard):
        """Test the display_latent_dashboards static method."""
        from interpretune.adapters.sae_lens import SAELensAnalysisMixin

        # Create mock metrics for testing
        mock_metrics = MagicMock()
        mock_metrics.total_effect = {
            "blocks.1.hook": torch.tensor([0.8, -0.5, 0.3, -0.9, 0.6]),
            "blocks.2.hook": torch.tensor([0.4, -0.7, 0.5, -0.2, 0.1]),
        }
        mock_metrics.num_samples_active = {
            "blocks.1.hook": torch.tensor([10, 15, 20, 25, 30]),
            "blocks.2.hook": torch.tensor([5, 10, 15, 20, 25]),
        }

        # Test with default top_k=1
        SAELensAnalysisMixin.display_latent_dashboards(
            metrics=mock_metrics, title="Test Dashboard", sae_release="test-release"
        )

        # Check expected print calls and display_dashboard calls for each hook and direction
        expected_print_calls = [
            call("\nTest Dashboard for blocks.1.hook:"),
            call("\npositive:"),
            call("#0 had total effect 0.80 and was active in 10 examples"),
            call("\nnegative:"),
            call("#3 had total effect -0.90 and was active in 25 examples"),
            call("\nTest Dashboard for blocks.2.hook:"),
            call("\npositive:"),
            call("#2 had total effect 0.50 and was active in 15 examples"),
            call("\nnegative:"),
            call("#1 had total effect -0.70 and was active in 10 examples"),
        ]
        mock_print.assert_has_calls(expected_print_calls)

        # Verify display_dashboard calls
        expected_display_calls = [
            call(sae_release="test-release", sae_id="blocks.1.hook_z", latent_idx=0),
            call(sae_release="test-release", sae_id="blocks.1.hook_z", latent_idx=3),
            call(sae_release="test-release", sae_id="blocks.2.hook_z", latent_idx=2),
            call(sae_release="test-release", sae_id="blocks.2.hook_z", latent_idx=1),
        ]
        mock_display_dashboard.assert_has_calls(expected_display_calls)

        # Test with custom hook_to_sae_id function and top_k=2
        mock_print.reset_mock()
        mock_display_dashboard.reset_mock()

        custom_hook_mapper = lambda hook: f"custom_mapping_for_{hook}"
        SAELensAnalysisMixin.display_latent_dashboards(
            metrics=mock_metrics,
            title="Custom Test",
            sae_release="custom-release",
            hook_to_sae_id=custom_hook_mapper,
            top_k=2,
        )

        # Verify custom mapping function was used for sae_id
        custom_display_calls = mock_display_dashboard.call_args_list
        assert any("custom_mapping_for_blocks.1.hook" in str(call) for call in custom_display_calls)
        assert any("custom_mapping_for_blocks.2.hook" in str(call) for call in custom_display_calls)

        # Verify top_k=2 resulted in more display calls (4 per hook: 2 positive + 2 negative)
        assert mock_display_dashboard.call_count == 8


################################################################################
# Cross-backend SAE module initialization tests
################################################################################


@pytest.fixture(scope="class")
def sl_ns_gpt2_module(get_it_session__sl_ns_gpt2__initonly):
    """NNsight SAE module from initonly fixture."""
    return get_it_session__sl_ns_gpt2__initonly.it_session.module


@pytest.fixture(scope="class")
def sl_ht_gpt2_module(get_it_session__sl_ht_gpt2__initonly):
    """HookedSAETransformer SAE module from initonly fixture (cross-backend init verification)."""
    return get_it_session__sl_ht_gpt2__initonly.it_session.module


@pytest.fixture(scope="class")
def sl_br_gpt2_module(get_it_session__sl_br_gpt2__initonly):
    """TransformerBridge SAE module from initonly fixture."""
    return get_it_session__sl_br_gpt2__initonly.it_session.module


cross_backend_init_pytest_cfg = {
    "argvalues": [
        pytest.param("sl_ht_gpt2_module", id="hooked_transformer"),
        pytest.param("sl_ns_gpt2_module", id="nnsight"),
        pytest.param("sl_br_gpt2_module", id="bridge"),
    ],
}


class TestCrossBackendSAEInit:
    """Tests that verify SAE initialization works across all three backends."""

    @pytest.mark.parametrize("session_fixture", **cross_backend_init_pytest_cfg)
    def test_sae_handles_loaded(self, request, session_fixture):
        """Verify SAE handles are loaded and non-empty for all backends."""
        module = request.getfixturevalue(session_fixture)
        assert len(module.sae_handles) > 0
        assert all(isinstance(h, SAE) for h in module.sae_handles)

    @pytest.mark.parametrize("session_fixture", **cross_backend_init_pytest_cfg)
    def test_saes_list_matches_handles(self, request, session_fixture):
        """Verify saes list and sae_handles are consistent."""
        module = request.getfixturevalue(session_fixture)
        assert len(module.saes) == len(module.sae_handles)
        for inst_sae, handle in zip(module.saes, module.sae_handles):
            assert inst_sae.handle is handle

    @pytest.mark.parametrize("session_fixture", **cross_backend_init_pytest_cfg)
    def test_model_initialized(self, request, session_fixture):
        """Verify model is initialized and accessible for all backends."""
        module = request.getfixturevalue(session_fixture)
        assert module.model is not None


class TestNNsightSAEBackend:
    """Tests specific to the NNsight SAE Lens backend."""

    def test_nnsight_config_validation(self):
        """Verify SAELensConfig with backend='nnsight' requires nnsight_cfg."""
        sae_cfg = SAELensFromPretrainedConfig(
            release="gpt2-small-res-jb", sae_id="blocks.0.hook_resid_pre", device="cpu"
        )
        with pytest.raises(MisconfigurationException, match="valid nnsight_cfg"):
            SAELensConfig(backend="nnsight", sae_cfgs=sae_cfg)

    def test_nnsight_config_rejects_invalid_backend(self):
        """Verify SAELensConfig rejects invalid backend strings."""
        sae_cfg = SAELensFromPretrainedConfig(
            release="gpt2-small-res-jb", sae_id="blocks.0.hook_resid_pre", device="cpu"
        )
        with pytest.raises(ValueError, match="Invalid backend"):
            SAELensConfig(backend="invalid_backend", sae_cfgs=sae_cfg)

    def test_nnsight_config_creation(self):
        """Verify SAELensConfig with backend='nnsight' initializes correctly."""
        sae_cfg = SAELensFromPretrainedConfig(
            release="gpt2-small-res-jb", sae_id="blocks.0.hook_resid_pre", device="cpu"
        )
        ns_cfg = NNsightConfig(
            model_name="openai-community/gpt2", device_map="cpu", torch_dtype="float32", dispatch=True
        )
        it_cfg = SAELensConfig(backend="nnsight", sae_cfgs=sae_cfg, nnsight_cfg=ns_cfg)
        assert it_cfg.backend == "nnsight"
        assert it_cfg.nnsight_cfg is not None
        assert it_cfg.model_name_or_path == "openai-community/gpt2"

    def test_nnsight_module_has_model_backend(self, sl_ns_gpt2_module):
        """Verify NNsight SAE module has a model_backend initialized."""
        from interpretune.analysis.backends.nnsight import NNsightModelBackend

        assert isinstance(sl_ns_gpt2_module.model_backend, NNsightModelBackend)

    def test_nnsight_module_tokenizer(self, sl_ns_gpt2_module):
        """Verify NNsight SAE module has a tokenizer available."""
        assert hasattr(sl_ns_gpt2_module.model, "tokenizer")
        assert sl_ns_gpt2_module.model.tokenizer is not None


class TestBridgeSAEBackend:
    """Tests specific to the TransformerBridge SAE Lens backend."""

    def test_bridge_config_creation(self):
        """Verify SAELensConfig with ITLensBridgeConfig initializes correctly."""
        sae_cfg = SAELensFromPretrainedConfig(
            release="gpt2-small-res-jb", sae_id="blocks.0.hook_resid_pre", device="cpu"
        )
        bridge_cfg = ITLensBridgeConfig(model_name="gpt2-small", default_padding_side="left")
        it_cfg = SAELensConfig(backend="transformerlens", tl_cfg=bridge_cfg, sae_cfgs=sae_cfg, use_bridge=True)
        assert it_cfg.backend == "transformerlens"
        assert isinstance(it_cfg.tl_cfg, ITLensBridgeConfig)

    def test_bridge_module_model_type(self, sl_br_gpt2_module):
        """Verify Bridge SAE module wraps an SAETransformerBridge."""
        from sae_lens.analysis.sae_transformer_bridge import SAETransformerBridge

        assert isinstance(sl_br_gpt2_module.model, SAETransformerBridge)

    def test_bridge_module_has_tl_backend(self, sl_br_gpt2_module):
        """Verify Bridge SAE module has a TL model backend initialized."""
        from interpretune.analysis.backends.transformer_lens import TLModelBackend

        assert isinstance(sl_br_gpt2_module.model_backend, TLModelBackend)


################################################################################
# TransformerBridge transcoder tests (lightweight, TINYSTORIES-based)
################################################################################

TINYSTORIES_MODEL = "tiny-stories-1M"
TRANSCODER_PROMPT = "Hello World!"


def _make_transcoder(d_model: int) -> Transcoder:
    """Create a transcoder: blocks.0.mlp.hook_in -> blocks.0.hook_mlp_out."""
    cfg = TranscoderConfig(
        d_in=d_model,
        d_sae=d_model * 2,
        d_out=d_model,
        apply_b_dec_to_input=False,
        metadata=SAEMetadata(
            hook_name="blocks.0.mlp.hook_in",
            hook_name_out="blocks.0.hook_mlp_out",
        ),
    )
    return Transcoder(cfg)


@pytest.fixture(scope="module")
def tinystories_bridge_model():
    """Lightweight SAETransformerBridge using tiny-stories-1M for transcoder tests."""
    from sae_lens.analysis.sae_transformer_bridge import SAETransformerBridge

    model = SAETransformerBridge.boot_transformers(TINYSTORIES_MODEL, device="cpu")
    yield model
    model.reset_saes()


@pytest.fixture(scope="module")
def tinystories_transcoder(tinystories_bridge_model):
    return _make_transcoder(tinystories_bridge_model.cfg.d_model)


@pytest.fixture(scope="module")
def tinystories_original_logits(tinystories_bridge_model):
    return tinystories_bridge_model(TRANSCODER_PROMPT)


class TestBridgeTranscoderSupport:
    """Tests for SAE transcoder support via SAETransformerBridge.

    Uses a lightweight tiny-stories-1M model booted directly as a TransformerBridge (bypassing the full Interpretune
    fixture factory) for fast, focused transcoder validation.
    """

    def test_add_transcoder_changes_output(
        self, tinystories_bridge_model, tinystories_transcoder, tinystories_original_logits
    ):
        """Adding a transcoder should change model output."""
        tinystories_bridge_model.add_sae(tinystories_transcoder)
        assert len(tinystories_bridge_model._acts_to_saes) == 1
        logits_with_transcoder = tinystories_bridge_model(TRANSCODER_PROMPT)
        assert not torch.allclose(tinystories_original_logits, logits_with_transcoder)
        tinystories_bridge_model.reset_saes()

    def test_transcoder_with_error_term_preserves_output(
        self, tinystories_bridge_model, tinystories_transcoder, tinystories_original_logits
    ):
        """Adding a transcoder with use_error_term=True should preserve output."""
        tinystories_bridge_model.add_sae(tinystories_transcoder, use_error_term=True)
        assert len(tinystories_bridge_model._acts_to_saes) == 1
        logits_with_transcoder = tinystories_bridge_model(TRANSCODER_PROMPT)
        tinystories_bridge_model.reset_saes()
        assert_close(tinystories_original_logits, logits_with_transcoder, atol=1e-4, rtol=0)

    def test_transcoder_reset_removes_transcoder(self, tinystories_bridge_model, tinystories_transcoder):
        """Resetting SAEs should remove the transcoder."""
        act_name = tinystories_transcoder.cfg.metadata.hook_name
        tinystories_bridge_model.add_sae(tinystories_transcoder)
        assert len(tinystories_bridge_model._acts_to_saes) == 1
        assert act_name in tinystories_bridge_model._acts_to_saes
        tinystories_bridge_model.reset_saes()
        assert len(tinystories_bridge_model._acts_to_saes) == 0

    def test_transcoder_context_manager(
        self, tinystories_bridge_model, tinystories_transcoder, tinystories_original_logits
    ):
        """Test transcoders via the saes() context manager."""
        assert len(tinystories_bridge_model._acts_to_saes) == 0
        with tinystories_bridge_model.saes(saes=[tinystories_transcoder]):
            assert len(tinystories_bridge_model._acts_to_saes) == 1
            logits_with_transcoder = tinystories_bridge_model(TRANSCODER_PROMPT)
            assert not torch.allclose(tinystories_original_logits, logits_with_transcoder)
        assert len(tinystories_bridge_model._acts_to_saes) == 0

    def test_transcoder_run_with_cache(
        self, tinystories_bridge_model, tinystories_transcoder, tinystories_original_logits
    ):
        """Test transcoders with run_with_cache_with_saes."""
        logits_with_transcoder, cache = tinystories_bridge_model.run_with_cache_with_saes(
            TRANSCODER_PROMPT, saes=[tinystories_transcoder]
        )
        assert logits_with_transcoder is not None
        assert isinstance(logits_with_transcoder, torch.Tensor)
        assert not torch.allclose(tinystories_original_logits, logits_with_transcoder)
        assert "blocks.0.mlp.hook_out.hook_sae_acts_post" in cache
        assert len(tinystories_bridge_model._acts_to_saes) == 0
