seed_everything: 42
data.class_path: interpretune.base.datamodules.ITDataModule
model.class_path: interpretune.base.modules.ITHookedModule
itdm_cfg:
  class_path: interpretune.config_classes.datamodule.ITDataModuleConfig
  init_args:
    task_name: override in experiment config
    model_name_or_path: override in experiment config
    data_collator_cfg:
      collator_class: transformers.DataCollatorWithPadding
    prompt_cfg:
      class_path: interpretune.config_classes.datamodule.PromptConfig
it_cfg:
  class_path: interpretune.config_classes.module.ITConfig
  init_args:
    use_model_cache: false
    from_pretrained_cfg:
      device_map: 0
      torch_dtype: bfloat16
