seed_everything: 42
session_cfg:
  datamodule_cfg:
    class_path: interpretune.config.datamodule.ITDataModuleConfig
  datamodule_cls: null
  module_cfg:
    class_path: interpretune.config.module.ITConfig
  module_cls: null
