name: Regen CI reqs runner
description: Install regen deps, run regen (pip-compile), and produce a patch if pins differ. Also performs checkout and Python setup.
inputs:
  python_version:
    description: 'Python version to setup'
    required: false
    default: '3.12'
  ci_output_dir:
    description: Directory where regen writes CI output (defaults to requirements/ci)
    required: false
    default: requirements/ci
  compare_paths:
    description: Space-separated list of files/paths to compare with git diff
    required: false
    default: "requirements/ci/requirements.txt requirements/ci/post_upgrades.txt requirements/ci/platform_dependent.txt"
  patch_path:
    description: Path to write the patch file
    required: false
    default: regen_diff.patch
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install regen deps
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install pip-tools toml

    - name: Run regen (pip-compile)
      shell: bash
      run: |
        python requirements/utils/regen_reqfiles.py --mode pip-compile --ci-output-dir=${{ inputs.ci_output_dir }}

    - id: check
      name: Check for diffs and write patch
      uses: ./.github/actions/check-file-diffs
      with:
        compare_paths: ${{ inputs.compare_paths }}
        patch_path: ${{ inputs.patch_path }}
        error_message: "CI requirements have changed and need to be regenerated"

outputs:
  changed:
    description: 'true if files differ'
    value: ${{ steps.check.outputs.changed }}
  patch_path:
    description: 'path to generated patch file'
    value: ${{ steps.check.outputs.patch_path }}
