seed_everything: 42
it_session:
  lightning: True
  datamodule_cfg:
    class_path: interpretune.base.config.datamodule.ITDataModuleConfig
    init_args:
      task_name: override in experiment config
      model_name_or_path: override in experiment config
      data_collator_cfg:
        collator_class: transformers.DataCollatorWithPadding
      prompt_cfg:
        class_path: interpretune.base.config.datamodule.PromptConfig
trainer:
  accumulate_grad_batches: 4
  accelerator: gpu
  strategy: auto
  precision: bf16-true
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: core_default
