seed_everything: 42
it_session:
  session_cfg:
    class_path: interpretune.base.contract.session.ITSessionConfig
trainer:
  accelerator: gpu
  strategy: auto
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: core_default
