seed_everything: 42
it_session:
  lightning: True
trainer:
  accelerator: gpu
  strategy: auto
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: core_default
