seed_everything: 42
data.class_path: interpretune.base.datamodules.ITLightningDataModule
model.class_path: interpretune.base.modules.ITLightningModule
itdm_cfg:
  class_path: interpretune.base.config.datamodule.ITDataModuleConfig
  init_args:
    task_name: override in experiment config
    model_name_or_path: override in experiment config
    data_collator_cfg:
      collator_class: transformers.DataCollatorWithPadding
    prompt_cfg:
      class_path: interpretune.base.config.datamodule.PromptConfig
it_cfg:
  class_path: interpretune.base.config.module.ITConfig
  init_args:
    use_model_cache: false
    from_pretrained_cfg:
      device_map: 0
      torch_dtype: bfloat16
    optimizer_init:
      class_path: torch.optim.AdamW
      init_args:
        weight_decay: 1.0e-06
        eps: 1.0e-07
        lr: 3.0e-05
    lr_scheduler_init:
      class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
      init_args:
        T_0: 1
        T_mult: 2
        eta_min: 1.0e-06
    pl_lrs_cfg:
      interval: epoch
      frequency: 1
      name: CosineAnnealingWithWarmRestartsLR
trainer:
  accumulate_grad_batches: 4
  accelerator: gpu
  strategy: auto
  precision: bf16-true
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: core_default
